# Generated by Django 4.0.5 on 2022-07-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_post_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fragmento',
            field=models.CharField(default='Click en el link que esta arriba para leer el post', max_length=255),
        ),
    ]
